# Generated by Django 5.1.6 on 2025-08-15 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20, unique=True)),
                ('MasterType', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_host', models.URLField(max_length=100)),
                ('sql_port', models.CharField(blank=True, max_length=10)),
                ('sql_username', models.CharField(max_length=100)),
                ('sql_password', models.CharField(max_length=100)),
                ('sql_database', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemParamDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('VchNo', models.CharField(max_length=10)),
                ('C1', models.CharField(blank=True, max_length=50)),
                ('C2', models.CharField(blank=True, max_length=50)),
                ('C3', models.CharField(blank=True, max_length=50)),
                ('C4', models.CharField(blank=True, max_length=50)),
                ('C5', models.CharField(blank=True, max_length=50)),
                ('D3', models.CharField(blank=True, max_length=50, verbose_name='mrp')),
                ('D4', models.CharField(blank=True, max_length=50, verbose_name='sale price')),
                ('BCN', models.CharField(blank=True, max_length=50)),
                ('Value1', models.FloatField(default=0)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.master1')),
            ],
        ),
    ]
