# Generated by Django 5.1.6 on 2025-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='server',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
