# Generated by Django 5.1.6 on 2025-08-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemparamdet',
            old_name='Item',
            new_name='ItemCode',
        ),
    ]
