# Generated by Django 5.1.6 on 2025-06-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20, unique=True)),
                ('MasterType', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemParamDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('VchType', models.CharField(max_length=10)),
                ('VchNo', models.CharField(max_length=10)),
                ('C1', models.CharField(blank=True, max_length=50)),
                ('C2', models.CharField(blank=True, max_length=50)),
                ('C3', models.CharField(blank=True, max_length=50)),
                ('C4', models.CharField(blank=True, max_length=50)),
                ('C5', models.CharField(blank=True, max_length=50)),
                ('BCN', models.CharField(blank=True, max_length=50)),
                ('Value1', models.FloatField(default=0)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1')),
            ],
        ),
    ]
