# Generated by Django 5.1.6 on 2025-06-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockreport', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemparamdet',
            options={'verbose_name': 'Item Parameter Detail', 'verbose_name_plural': 'Item Parameter Details'},
        ),
        migrations.AlterModelOptions(
            name='master1',
            options={'verbose_name': 'Master Item', 'verbose_name_plural': 'Master Items'},
        ),
    ]
