# Generated by Django 5.1.6 on 2025-08-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_rename_item_itemparamdet_itemcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterStockView',
            fields=[
            ],
            options={
                'verbose_name': 'Parameter Stock Detail',
                'verbose_name_plural': 'Parameter Stock Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.itemparamdet',),
        ),
        migrations.CreateModel(
            name='StockReportView',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.master1',),
        ),
    ]
